<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<OutputPath>$(SolutionDir)$(Platform)\$(Configuration)\</OutputPath>
	<PlatformTarget>$(Platform)</PlatformTarget>
	<Platforms>x86;x64</Platforms>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<RunWorkingDirectory>$(OutputPath)</RunWorkingDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core-clrbridge\core-clrbridge.vcxproj" />
  </ItemGroup>

</Project>